server:
  port: 8081
  # When running behind a reverse proxy, this strategy needs to be set to ensure
  # that OpenAPI endpoint returns the correct server URLs
  # https://springdoc.org/faq.html#_how_can_i_deploy_springdoc_openapi_ui_behind_a_reverse_proxy
  forward-headers-strategy: framework

where-for-dinner:
  searchEvent:
    period: 120000
    
spring:
  sql.init.mode: ALWAYS 
  sql.init.platform: h2

  cloud: 
    stream:
      poller:
        fixed-delay: ${where-for-dinner.searchEvent.period} 
      function:
        definition: submittedSearches
      bindings: 
        submittedSearches-out-0: 
          destination: where-for-dinner-search-criteria
      servicebus:
        bindings:
          submittedSearches-out-0:
            producer:
              entity-type: topic

springdoc:
  packages-to-scan: com.java.example.tanzu.wherefordinner.resources
  show-spring-cloud-functions: false
    
---

spring:
  config.activate.on-profile: postgres
  
  sql.init.platform: postgresql
